#!/bin/bash

# webm-by-dbt v1.5.2

# extract file name from input file path
infile=$(basename "$1")

# write source file name into log file and stdout
mkdir "./webm"
echo "converting $1:" | tee -a "./webm/$infile.log"

# loop until user uses keyboard interrupt
while true
do
    # get user input
    echo "start time (hh:mm:ss.t)"
    read start
    echo "duration (seconds[.decimals])"
    read duration
    echo "y-resolution {720, 540, 360; original if empty}"
    read v_res
    echo "audio? [y|N]"
    read audio
    echo "output file name"
    read output

    # calculate secondary params
    if [[ "$v_res" = "720" ]]
    then
        rescmd="-s 1280:720"
    elif [[ "$v_res" = "540" ]]
    then
        rescmd="-s 960:540"
    elif [[ "$v_res" = "360" ]]
    then
        rescmd="-s 640:360"
    elif [[ "$vres" = "" ]]
    then
        rescmd=""
    else
        echo "invalid resolution"
        exit
    fi
    if [[ "$audio" = "y" ]]
    then
        audiocmd="-c:a libvorbis -b:a 192K -vbr on -ac 2"
        maxsize=3800
    else
        audio="N"
        audiocmd="-an"
        maxsize=3000
    fi
    bitrate=$(echo "(8*$maxsize/$duration)" | bc)

    # write user params into stdout and logfile
    echo "-----------------------" | tee -a "./webm/$infile.log"
    echo "start:       $start" | tee -a "./webm/$infile.log"
    echo "duration:    $duration s" | tee -a "./webm/$infile.log"
    echo "max bitrate: $bitrate kbps" | tee -a "./webm/$infile.log"
    echo "output file: ./webm/$output.webm" | tee -a "./webm/$infile.log"
    echo "resolution:  $rescmd" | tee -a "./webm/$infile.log"
    echo "audio:       $audiocmd" | tee -a "./webm/$infile.log"
    echo "Press [Enter] to start converting!"
    read confirm

    # first pass
    echo "ffmpeg -y -ss \"$start\" -t \"$duration\" -i \"$1\" -c:v libvpx -pass 1 -qmin 0 -qmax 50 -crf 10 -b:v 1M -threads 3 -speed 4 -an -f webm \"/dev/null\""
    ffmpeg -y -ss "$start" -t "$duration" -i "$1" -c:v libvpx -pass 1 -qmin 0 -qmax 50 -crf 10 -b:v 1M -threads 3 -speed 4 -an -f webm "/dev/null"

    # second pass
    echo "ffmpeg -ss \"$start\" -t \"$duration\" -i \"$1\" -c:v libvpx -pass 2 -qmin 0 -qmax 50 -crf 10 -b:v \"$bitrate\" $rescmd \"$audiocmd\" -threads 3 -speed 0 -f webm -metadata title=\"$infile start $start length $duration\" \"./webm/$output.webm\""
    ffmpeg -ss "$start" -t "$duration" -i "$1" -c:v libvpx -pass 2 -qmin 0 -qmax 50 -crf 10 -b:v "$bitrate"k $rescmd "$audiocmd" -threads 3 -speed 0 -f webm -metadata title="$infile start $start length $duration" "./webm/$output.webm"
    
    echo ""
done
echo "" | tee -a "./webm/$infile.log"
echo "Exiting."
